version: '2.0'

networks:
  birthdays-page-net:
    driver: bridge

services:
  jenkins-master:
    image: artifactory.esl.corp.elbit.co.il/aerospace-simulators-devops-docker/birthdays-page-nodejs:14
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: birthdays-page
    volumes:
      - ./data:/birthdays-page-container/data
    restart: always
    ports:
      - "4123:4123"
    healthcheck:
      test: ["CMD", "curl", "-s", "-k", "--fail", "http://localhost:4123/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - birthdays-page-net
    environment:
      # BIRTHDAYS_SERVER_HOST: "0.0.0.0"  # <-- Open for everyone
      BIRTHDAYS_SERVER_HOST: "127.0.0.1"
      BIRTHDAYS_SERVER_PORT: "4123"
